apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crj-postgres-ingestion
  namespace: app
spec:
  schedule: "0 0 */1 * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-postgres-ingestion
            image: gersonrs/ingestion-data-stores:v1.5.0 # x-release-please-version
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","postgres"]
          restartPolicy: OnFailure
