apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crj-mssql-ingestion
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crj-mssql-ingestion
            image: gersonrs/ingestion-data-stores:v1.5.0 # x-release-please-version
            imagePullPolicy: IfNotPresent
            command: ["python3.9","cli.py","mssql"]
          restartPolicy: OnFailure
